### ISSUE TITLE
Make 'Launch email' button open in a new tab

### ISSUE THREAD

**Issue by heyrocker** [Lullabot/fivefifteen#58]
This change would prevent those of us <cough> who always seem to press the button without copying the text from losing all their work and bursting into tears on a weekly basis.

**Comment by deviantintegral** [comment]
I've done the same in Firefox, and clicking back has preserved the form for me. Might be an easy workaround?

**Comment by heyrocker** [comment]
It didn't preserve the form for me in chrome.

On Tuesday, May 12, 2015, Andrew Berry <notifications@github.com> wrote:

> I've done the same in Firefox, and clicking back has preserved the form
> for me. Might be an easy workaround?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lullabot/fivefifteen/issues/58#issuecomment-101342472>
> .
>


-- 
Greg Dunlap
Senior Architect  |  Lullabot

e:  greg.dunlap@lullabot.com
w: http://lb.cm/heyrocker
t:  http://twitter.com/heyrocker

**Comment by q0rban** [comment]
I think the real solution is to figure out why local storage isn't working. #43 works on my local, but not in "production"

**Comment by sirkitree** [comment]
actually looking in master, we can just use window.open instead of window.location.href and that will launch this in a new window. However I can't get master to build correctly currently :frowning:

**Comment by sirkitree** [comment]
ok, i didn't have compass installed, now it's building. merging this.

**Comment by sirkitree** [comment]
Works. Testing in latest Chrome and FIrefox36
