### ISSUE TITLE
npm install error for karma-requirejs

### ISSUE THREAD

**Issue by jasonruyle** [Lullabot/fivefifteen#60]
You need to update the project.json file for karma-requirejs from/to:

```
"karma-requirejs": "~0.1.0",
```

to

```
"karma-requirejs": "~0.2.0",
```

**Comment by kae76** [comment]
Found the same issue.

The file to edit is: package.json

**Comment by sirkitree** [comment]
Thanks! Done.

**Comment by kae76** [comment]
Hey thanks, sorry I was being a bit lazy - I should've done a PR. :)
