### ISSUE TITLE
Remove descriptive text on copy

### ISSUE THREAD

**Issue by mettamatt** [Lullabot/fivefifteen#61]
I use this site every week. Love it!

Can we consider removing the descriptive text for each question from the copy/paste textfield at the end of the process?  I remove it manually, and I ask those that submit 515's to me to remove it was well before sending me the update so I can read it easier.

**Comment by sirkitree** [comment]
We should probably use an option for this because some people prefer having it in place. See #15 for previous discussion around this.

**Comment by q0rban** [comment]
#dejametta

**Comment by mettamatt** [comment]
I don't mind continuing to remove the descriptions manually. Just curious of others are doing the same.
